### ISSUE TITLE
CLI package is not output full help information.

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#36]
**What is the issue about**:

CLI package is not output full help information.

**What happened**:

```
$ ./cli -h       
this is an cli example

Usage:
  example [flags]

Flags:
  -h, --help   help for example
```

**What you expected to happen**:

```
$ ./cli -h       
this is an cli example

Usage:
  example [flags]

Flags:
  -h, --help   help for example
  -l, --log      blabla
  -d, --dev    blabla
```

**Anything else we need to know**:

This is built from cli example. @zoumo

**Comment by zoumo** [comment]
This issue is in expected because you set `Deprecated`, `ShorthandDeprecated` or `Hidden` for flag `log` and `dev`

in `pflag`
- `Deprecated`, `Hidden`  will hide the whole flag in help information.
- `ShorthandDeprecated` will hide the shorthand flag.

but you can set the flag as usual.

- `Hidden` just hide the flag
- `Deprecated` and `ShorthandDeprecated` will print a deprecated message to you if you use the flag

**Comment by zoumo** [comment]
I think this should be mentioned in flags comments

**Comment by ddysher** [comment]
Thanks!  Close via #37

@zoumo Please make sure related issues are closed.
